### Code.1-1-1: Affine Function

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

# vector가 아닌 matrix 형태로 생성 [[10.]]
# x는 input
x = tf.constant([[10.]]) # input setting, input은 Matrix 형태로 주어야 함

# w, b를 줌
# 하나의 dense layer 생성(units=1)
# dense = Dense(units=1) # imp. an affine function
dense = Dense(units=1, activation='linear') # default: linear

# z = x*w + b
# dense 연산을 수행하기 전까지, w, b는 초기화되지 x
y_tf = dense(x) # y 값을 연산, forward propagation + params initialization

W, B = dense.get_weights() # get weight, bias

# y_tf가 matfix이기 때문에, matrix multipulication 필요
# 행렬 곱셈을 증명하는 과정
y_man = tf.linalg.matmul(x, W) + B # forward propagation(manual)

# print result
print('===== Input/Weight/Bias =====')
print(f'x: {x.shape}\n{x.numpy()}\n')
print(f'W: {W.shape}\n{W}\n')
print(f'b: {B.shape}\n{B}\n')


print('===== Outputs =====')
print(f'y(Tensorflow): {y_tf.shape}\n{y_tf.numpy()}\n')
print(f'y(Manual): {y_man.shape}\n{y_man.numpy()}\n')

===== Input/Weight/Bias =====
x: (1, 1)
[[10.]]

W: (1, 1)
[[0.96020997]]

b: (1,)
[0.]

===== Outputs =====
y(Tensorflow): (1, 1)
[[9.602099]]

y(Manual): (1, 1)
[[9.602099]]



### Code.1-1-1: Params Initialization

In [19]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant


x = tf.constant([[10.]]) # input setting, input은 Matrix 형태로 주어야 함

# weight/bias setting
# weight와 bias를 manual하게 생성
w, b = tf.constant(10.), tf.constant(20.)
# tensor 값이 아닌, tensor를 초기화 하기 위한 객체임(그대로 사용 불가)
w_init, b_init = Constant(w), Constant(b)

# imp. an affine function
dense = Dense(units=1,
              activation='linear', 
              kernel_initializer=w_init,
              bias_initializer=b_init
              )

y_tf = dense(x)
print(y_tf) # tensor=120, 10*10 + 20
W, B = dense.get_weights()

# print results
print(f'W: {W.shape}\n{W}\n')
print(f'b: {B.shape}\n{B}\n')
print(w_init, b_init)

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
[[10.]]

b: (1,)
[20.]

<keras.initializers.initializers_v2.Constant object at 0x7fcfb1178670> <keras.initializers.initializers_v2.Constant object at 0x7fcfaaa9d6d0>


## 1.2: Affine Functions with N Features

### Code.1-2-1: Affine Functions with n Features

In [27]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

# uniform: 0~10 까지 값을 골고루 추출
x=tf.random.uniform(shape=(1, 10), minval=0, maxval=10)
print(x.shape, '\n', x)

dense = Dense(units=1)

# 해당 시점에 x의 상태를 보고 (10, 1), 1 형태의 W, b 생성
# x와 transpose한 형태로 ->w 생성
y_tf = dense(x)

W, B = dense.get_weights()

# 내용 검증을 위한 manual 연산
# z = x*W + B
y_man = tf.linalg.matmul(x, W) + B

# print result
print('===== Input/Weight/Bias =====')
print(f'x: {x.shape}\n{x.numpy()}\n')
print(f'W: {W.shape}\n{W}\n')
print(f'b: {B.shape}\n{B}\n')


print('===== Outputs =====')
print(f'y(Tensorflow): {y_tf.shape}\n{y_tf.numpy()}\n')
print(f'y(Manual): {y_man.shape}\n{y_man.numpy()}\n')

(1, 10) 
 tf.Tensor(
[[1.1354065 9.470696  9.7195635 2.368126  9.49297   9.681764  4.704883
  6.1133003 7.919662  7.7857304]], shape=(1, 10), dtype=float32)
===== Input/Weight/Bias =====
x: (1, 10)
[[1.1354065 9.470696  9.7195635 2.368126  9.49297   9.681764  4.704883
  6.1133003 7.919662  7.7857304]]

W: (10, 1)
[[-0.27847493]
 [ 0.21436703]
 [-0.21050924]
 [-0.53775144]
 [-0.3315008 ]
 [ 0.07441759]
 [-0.70547473]
 [ 0.5499378 ]
 [ 0.18493801]
 [ 0.6325504 ]]

b: (1,)
[0.]

===== Outputs =====
y(Tensorflow): (1, 1)
[[2.4003406]]

y(Manual): (1, 1)
[[2.4003406]]

