# 4-1: Datasets
- 원하는 데이터셋을 만드는 방법을 중심으로 작업
- Dataset을 쪼개서 사용 -> Minibatch

## Code.4-1-1: Dataset for Regression

In [ ]:
import tensorflow as tf

N, n_feature = 8, 5
t_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
t_bias = tf.constant([10], dtype=tf.float32)

print(t_weights)
print(t_bias)

# 8x5
X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
print(X.shape, t_weights.shape, t_bias.shape)

# Y = t_weights * X + t_bias
# print(f"{X.shape}\n{X}")
# print(f"{Y.shape}\n{Y}")

# axis=1을 기준으로 합계 구하기(X축 기준)
Y = tf.reduce_sum(t_weights*X, axis=1) + t_bias
# print(X.shape, Y.shape)
print(f"X(shape/dtype/data): {X.shape} / {X.dtype} \n {X.numpy}")
print(f"Y(shape/dtype/data): {Y.shape} / {Y.dtype} \n {Y.numpy}")

# linear regression 식
# y = 1*x1 + 2*x2 + ... 5*x5 + 10
# \hat{y} = w1x1 + w2x2 + ... + w5x5 + b
# 위 아래가 유사할 수록 학습이 잘 되는 것

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([10.], shape=(1,), dtype=float32)
(8, 5) (5,) (1,)
X(shape/dtype/data): (8, 5) / <dtype: 'float32'> 
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(8, 5), dtype=float32, numpy=
array([[ 0.38013113,  0.02481292, -1.2147615 ,  0.08325492, -0.06607852],
       [-0.6023226 , -0.12577854,  0.44385794,  0.09283901,  0.61280924],
       [ 1.622178  ,  1.0945451 , -0.5179834 ,  0.32299107,  0.04143976],
       [-0.20255233, -0.07608757, -0.12386128,  2.5107954 ,  0.83958566],
       [-0.17557956, -2.0125186 , -0.3844421 , -0.8078473 , -1.6375234 ],
       [ 0.00691745,  0.12919182,  1.2423631 , -0.54613954, -0.06957775],
       [-1.2073375 ,  0.51631683, -1.2019142 , -1.2838805 , -1.9230932 ],
       [ 1.0377922 ,  0.85911614,  0.08332924, -0.0306763 , -0.73843324]],
      dtype=float32)>>
Y(shape/dtype/data): (8,) / <dtype: 'float32'> 
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(8,), dtype=float32, n

## Code.4-1-2: Dataset for Binary Classification

In [ ]:
import tensorflow as tf

N, n_feature = 8, 5
t_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
t_bias = tf.constant([10], dtype=tf.float32)

print(t_weights)
print(t_bias)

# 8x5
X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
Y = tf.reduce_sum(t_weights*X, axis=1) + t_bias
print(Y)
# 5보다 클경우, 아닐 경우에 따라 True, False -> bool 변경
Y = Y > 5
print(Y)
Y = tf.cast(Y, tf.int32)
print(Y)

print(f"X(shape/dtype/data): {X.shape} / {X.dtype} \n {X.numpy}")
print(f"Y(shape/dtype/data): {Y.shape} / {Y.dtype} \n {Y.numpy}")


tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([10.], shape=(1,), dtype=float32)
tf.Tensor(
[13.921053    7.8079963  -4.326666   16.776485   -0.66728973  4.8418226
  4.6454306   7.821409  ], shape=(8,), dtype=float32)
tf.Tensor([ True  True False  True False False False  True], shape=(8,), dtype=bool)
tf.Tensor([1 1 0 1 0 0 0 1], shape=(8,), dtype=int32)
X(shape/dtype/data): (8, 5) / <dtype: 'float32'> 
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(8, 5), dtype=float32, numpy=
array([[ 1.6628288 ,  0.18992615, -0.59344774, -0.15649576,  0.85693973],
       [-0.8558225 ,  0.10739316,  0.60196954,  0.28160006, -0.8966553 ],
       [ 0.48276547, -0.31818023, -0.7626572 , -1.5525278 , -1.1349976 ],
       [-0.9008737 ,  1.3472229 ,  1.2136518 , -1.0241427 ,  1.0877059 ],
       [-1.490965  , -1.8689486 , -1.4615862 ,  0.8635986 , -0.90161276],
       [ 1.8893863 ,  0.73389894, -0.9030624 , -0.1937437 , -1.0062399 ],
       [ 0.4924372 ,  0.06823647, -1.82182