# 2-1: Dense Layers

## *Code*.2-1-1: Shapes of Dense Layers

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

# X = ((->x^(1))^T (->x^(2))^T ... (->x^(N))^T) 의 input 생성
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')

# X 통과, 이 dense layer는 3개의 뉴런을 가짐
# 하나의 neuron은 weight vector(10), bias(3)을 가지며
# 최종적으로 W = 10 x 3, bias = vector(3)을 가짐
Y_tf = dense(X)

# 실제 이론처럼 생성되었는지 검증
W, B = dense.get_weights()
print('===== Input/Weight/Bias =====')
print(f"X: {X.shape}")
print(f"W: {W.shape}")
print(f"B: {B.shape}")

# output vector = 1 x 3
print(f"Y: {Y_tf.shape}")
# 하나의 컬럼당, 하나의 neuron의 weight을 의미 
print(W)

print(f"Y(Tensorflow): \n {Y_tf.numpy()}")

# calculate with matrix multiplication
Z = matmul(X, W) + B
Y_man_matmul = 1/(1 + exp(-Z))
print(f"Y(with matrix multiplication: \n {Y_man_matmul.numpy()}")

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron)) # 4 x 3
for x_idx in range(N):
  x= X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]
    z = tf.reduce_sum(x * w) + b
    a = 1/(1 + np.exp(-z))
    Y_man_vec[x_idx,nu_idx] = a

print(f"Y(with dot producs): \n {Y_man_vec}")

===== Input/Weight/Bias =====
X: (4, 10)
W: (10, 3)
B: (3,)
Y: (4, 3)
[[ 0.37309587  0.5083232   0.57203555]
 [-0.20396599  0.41426826 -0.6501371 ]
 [-0.04777634 -0.14888108  0.59533775]
 [-0.3140095   0.28504556  0.5382954 ]
 [ 0.28961533  0.515494   -0.22214508]
 [ 0.49318564  0.42322326  0.08159399]
 [ 0.3615675  -0.54739183  0.2144661 ]
 [ 0.11891192 -0.4982126   0.360515  ]
 [-0.63547677  0.19937742 -0.55581915]
 [-0.5465478   0.18854302  0.08994973]]
Y(Tensorflow): 
 [[0.58275586 0.3564469  0.9363217 ]
 [0.941601   0.29220355 0.7902023 ]
 [0.6787915  0.5817162  0.39256167]
 [0.12157147 0.45740062 0.5984683 ]]
Y(with matrix multiplication: 
 [[0.5827559  0.3564469  0.9363217 ]
 [0.941601   0.29220355 0.7902024 ]
 [0.6787915  0.5817161  0.39256167]
 [0.12157147 0.4574006  0.59846836]]
Y(with dot producs): 
 [[0.58275592 0.35644683 0.93632167]
 [0.94160098 0.2922035  0.79020233]
 [0.67879154 0.58171617 0.39256164]
 [0.12157145 0.45740062 0.59846832]]


## Code.2-1-2: Output Calculations

# 2-2: Cascaded Dense Layers

## *Code*.2-1-2: Shapes of Cascaded Dense Layers

In [10]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

# 첫번째 layer에는 3개의 neuron
# 두번째 layer에는 5개의 neuron
n_neurons = [3,5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print(f"X: {X.shape}\n")
print(f"W1: {W1.shape}\n")
print(f"B1: {B1.shape}\n")
print(f"A1: {A1.shape}\n")

print(f"W2: {W2.shape}\n")
print(f"B2: {B2.shape}\n")
print(f"Y: {Y.shape}\n")

X: (4, 10)

W1: (10, 3)

B1: (3,)

A1: (4, 3)

W2: (3, 5)

B2: (5,)

Y: (4, 5)




## Code.2-2-2: Dense Layers with Python List


In [15]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

# 여러개의 Dense Layer를 활용할때 python list를 활용하는 방법
n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()
# 10개의 dense layer(object) 존재
for n_neuron in n_neurons:
  print(n_neuron)
  dense = Dense(units=n_neuron, activation='relu')
  dense_layers.append(dense)

print(f"Input: {X.shape}")
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  print(f"After dense layer: {dense_idx+1}")
  print(f"{X.shape} \n")

Y = X

10
20
30
40
50
60
70
80
90
100
Input: (4, 10)
After dense layer: 1
(4, 10) 

After dense layer: 2
(4, 20) 

After dense layer: 3
(4, 30) 

After dense layer: 4
(4, 40) 

After dense layer: 5
(4, 50) 

After dense layer: 6
(4, 60) 

After dense layer: 7
(4, 70) 

After dense layer: 8
(4, 80) 

After dense layer: 9
(4, 90) 

After dense layer: 10
(4, 100) 




## Code.2-2-3: Output Calculations

In [24]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
# 초기 입력값이 계속 overwrite되기 때문에 사전 복사
X_cp = tf.identity(X)

n_neurons = [3, 4, 5]

dense_layers = list()
# 10개의 dense layer(object) 존재
for n_neuron in n_neurons:
  print(n_neuron)
  dense = Dense(units=n_neuron, activation='sigmoid')
  dense_layers.append(dense)

# forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b= dense.get_weights()

  W.append(w)
  B.append(b)
print(f"Y(Tensorflow): \n {X.numpy()}")

# forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1 + exp(-X_cp))

print(f"Y(Manual): \n {X.numpy()}")

3
4
5
Y(Tensorflow): 
 [[0.68722385 0.5434971  0.56987685 0.5091848  0.41130427]
 [0.6696428  0.5908019  0.5510873  0.4835227  0.39039767]
 [0.69718885 0.53936    0.5714452  0.50411856 0.41936702]
 [0.66156363 0.6007167  0.54580283 0.47864518 0.3855614 ]]
Y(Manual): 
 [[0.68722385 0.5434971  0.56987685 0.5091848  0.41130427]
 [0.6696428  0.5908019  0.5510873  0.4835227  0.39039767]
 [0.69718885 0.53936    0.5714452  0.50411856 0.41936702]
 [0.66156363 0.6007167  0.54580283 0.47864518 0.3855614 ]]
