# 5-1: Conv Layers

## Code.5-1-1: Shapes of Conv Layers

In [7]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

# 4차원이 사용됨
# 갯수, 높이, 너비, 색
N, n_H, n_W, n_C = 1, 28, 28, 5
n_filter = 1
f_size = 3 # filter size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=f_size)
y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape) # kernel size (3x3x5)
print(B.shape)
print(y.shape) # 결과로 하나의 이미지 생성 26x26

(1, 28, 28, 5)
(3, 3, 5, 1)
(1,)
(1, 26, 26, 1)


## Code.5-1-2: Correlation Calculation

In [23]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Conv2D

# 4차원이 사용됨
# 갯수, 높이, 너비, 색
N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3 # filter size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=f_size)
y = conv(images)
# numpy().squeeze() -> 1을 제거
## e.g. (1, 26, 26, 1) -> (26, 26)
print(f"Y(Tensorflow): {y.numpy().squeeze()}")

W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()
# print(images.shape)
# print(W.shape)
# print(B.shape)
y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size +1):
  for j in range(n_W - k_size + 1):
    window = images[i:i+k_size,j:j+k_size]
    y_man[i,j] = np.sum(window*W) + B

print(f"Y(Manual): {y_man}")

Y(Tensorflow): [[-0.33534825  0.2108254  -0.29154325]
 [ 0.03141999 -0.35618237 -0.0872623 ]
 [ 0.46976927 -0.10988952 -0.15373021]]
Y(Manual): [[-0.33534828  0.2108254  -0.29154328]
 [ 0.03141999 -0.3561824  -0.08726229]
 [ 0.46976927 -0.10988951 -0.15373024]]


## Code.5-1-3. Correlation with n-channel

In [24]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Conv2D

# 4차원이 사용됨
# 갯수, 높이, 너비, 색
N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3 # filter size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=f_size)
y = conv(images)
# numpy().squeeze() -> 1을 제거
## e.g. (1, 26, 26, 1) -> (26, 26)
print(f"Y(Tensorflow): {y.numpy().squeeze()}")

W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()
# print(images.shape)
y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size +1):
  for j in range(n_W - k_size + 1):
    window = images[i:i+k_size,j:j+k_size, :]
    y_man[i,j] = np.sum(window*W) + B

print(f"Y(Manual): {y_man}")

Y(Tensorflow): [[0.63634044 0.7204193  0.6446288 ]
 [0.4445445  0.6329689  0.33772513]
 [0.31513533 0.7005405  0.4827827 ]]
Y(Manual): [[0.63634044 0.72041941 0.64462876]
 [0.44454455 0.63296902 0.33772519]
 [0.31513539 0.70054048 0.48278266]]
