# 6-1: Max/Avg Pooling

## Code.6-1-1: Max Pooling

In [7]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1,L,1))
pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print(f"x: {x.shape}\n{x.numpy().flatten()}")
print(f"pooled_max(Tensorflow: {pooled_max.shape}\n{pooled_max.numpy().flatten()}")
# X[0], x[1]에서 큰 값이 pooled_max[0]에 들어감
# X[1], X[2]중 큰 값이 pooled_max[1]에 들어감

x = x.numpy().flatten()
pooled_max_man = np.zeros((L -f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i] = np.max(window)

print(f"pooled_max(Manual): {pooled_max_man.shape}\n{pooled_max_man}")

x: (1, 10, 1)
[ 1.5459614   0.8055384  -0.2364404  -0.01395386  0.40516183 -0.9007081
 -0.65948164  0.76827824 -0.36108506 -0.4274324 ]
pooled_max(Tensorflow: (1, 9, 1)
[ 1.5459614   0.8055384  -0.01395386  0.40516183  0.40516183 -0.65948164
  0.76827824  0.76827824 -0.36108506]
pooled_max(Manual): (9,)
[ 1.54596138  0.80553842 -0.01395386  0.40516183  0.40516183 -0.65948164
  0.76827824  0.76827824 -0.36108506]


## Code.6-1-2: Average Pooling
- MaxPooling1D -> AveragePooling1D로 변경

In [10]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1,L,1))
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print(f"x: {x.shape}\n{x.numpy().flatten()}")
print(f"pooled_max(Tensorflow: {pooled_avg.shape}\n{pooled_avg.numpy().flatten()}")

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L -f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  # np.mean을 사용
  pooled_avg_man[i] = np.mean(window)

print(f"pooled_avg(Manual): {pooled_avg_man.shape}\n{pooled_avg_man}")

x: (1, 10, 1)
[-0.13637772 -0.46194535 -1.6872281  -1.4459666   0.5508127   0.2935276
 -0.40580183 -1.0686089  -1.9519523   1.0728288 ]
pooled_max(Tensorflow: (1, 9, 1)
[-0.29916155 -1.0745867  -1.5665973  -0.44757694  0.42217016 -0.05613711
 -0.7372054  -1.5102806  -0.43956178]
pooled_avg(Manual): (9,)
[-0.29916155 -1.07458675 -1.56659734 -0.44757694  0.42217016 -0.05613711
 -0.73720539 -1.51028061 -0.43956178]


# 6-2: 2D Max/Avg Pooling

## Code.6-2-1: 2D Max Pooling

In [16]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

# X의 인접 4개의 원소의 가장 큰 값이 pooled_max의 하나로 귀결
print(f"x: {x.shape}\n{x.numpy().squeeze()}")
print(f"pooled_max(Tensorflow: {pooled_max.shape}\n{pooled_max.numpy().squeeze()}")

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H -f + 1, n_W -f + 1))
for i in range(n_H -f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j] = np.max(window)

print(f"pooled_max(Manual): {pooled_max_man.shape}\n{pooled_max_man}")

x: (1, 5, 5, 1)
[[-0.5607652   0.0617762   0.9109229   1.5853728   1.8214817 ]
 [-0.5145496   0.16694617 -0.3177714   0.7596231   0.7290873 ]
 [-0.8604334   1.527618    0.908652   -0.09826467 -0.3260797 ]
 [-0.30398038  0.89429486  1.3196851  -0.9951535  -0.5313618 ]
 [ 0.5857642  -1.3249868  -0.16299419 -1.2727414   0.677228  ]]
pooled_max(Tensorflow: (1, 4, 4, 1)
[[ 0.16694617  0.9109229   1.5853728   1.8214817 ]
 [ 1.527618    1.527618    0.908652    0.7596231 ]
 [ 1.527618    1.527618    1.3196851  -0.09826467]
 [ 0.89429486  1.3196851   1.3196851   0.677228  ]]
pooled_max(Manual): (4, 4)
[[ 0.16694617  0.91092288  1.58537281  1.8214817 ]
 [ 1.52761805  1.52761805  0.90865201  0.75962311]
 [ 1.52761805  1.52761805  1.3196851  -0.09826467]
 [ 0.89429486  1.3196851   1.3196851   0.67722797]]


## Code.6-2-1: 2D Average Pooling

In [19]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_max(x)

# X의 인접 4개의 원소의 가장 큰 값이 pooled_max의 하나로 귀결
print(f"x: {x.shape}\n{x.numpy().squeeze()}")
print(f"pooled_avg(Tensorflow: {pooled_avg.shape}\n{pooled_avg.numpy().squeeze()}")

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H -f + 1, n_W -f + 1))
for i in range(n_H -f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i, j] = np.max(window)

print(f"pooled_avg(Manual): {pooled_avg_man.shape}\n{pooled_avg_man}")

x: (1, 5, 5, 1)
[[-0.37739685  0.12936793 -0.07290127 -0.430454   -0.8371021 ]
 [-1.2261372   0.6314146   0.26232037  0.8495148   0.27755046]
 [ 0.42827898  0.46426526 -0.17955576 -0.60707486 -0.48140225]
 [ 0.00477986  1.0105821   0.2827803  -0.90951693 -0.9202095 ]
 [-1.2784076   0.22387998 -0.08198547  0.18604328  0.10331965]]
pooled_avg(Tensorflow: (1, 4, 4, 1)
[[ 0.6314146   0.6314146   0.8495148   0.8495148 ]
 [ 0.6314146   0.6314146   0.8495148   0.8495148 ]
 [ 1.0105821   1.0105821   0.2827803  -0.48140225]
 [ 1.0105821   1.0105821   0.2827803   0.18604328]]
pooled_avg(Manual): (4, 4)
[[ 0.63141459  0.63141459  0.84951478  0.84951478]
 [ 0.63141459  0.63141459  0.84951478  0.84951478]
 [ 1.01058209  1.01058209  0.28278029 -0.48140225]
 [ 1.01058209  1.01058209  0.28278029  0.18604328]]
