# 5-2: Conv Layers with Filters

## Code.5-2-1: Shapes with Filters
- 가장 쉬운 검증 방법은 shape 검증

In [4]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

# N은 데이터의 수, 변하지 않음
N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3 # kernel, color size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)

W, B = conv.get_weights()

print(f"input images: {images.shape}")
print(f"W/B: {W.shape}/{B.shape}") # kernel size (3x3x5)
print(f"Output image: {Y.shape}")

input images: (32, 28, 28, 3)
W/B: (3, 3, 3, 5)/(5,)
Output image: (32, 26, 26, 5)


## Code.5-2-2: Computations with Filters

In [31]:
import numpy as np
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4 # kernel, color size
images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)
# print(Y.shape)
print(Y.numpy().shape)
# print(f"Y(Tensorflow): {Y.numpy()}")
# (1, 2, 2, 4) 형태를 출력
# 마치 kernel(R,G,B)에 해당하는 값이 4로 출력됨에 따라
# 결과는 R,G,B,_가 펼쳐진 형태로 print됨

Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print(f"Y(Tensorflow): {Y}")

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()
# print(W.shape, B.shape)

Y_man = np.zeros(shape=(n_H - k_size +1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:,:,:,c]
  c_b = B[c]

  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w+k_size, :]
      conv = np.sum(window*c_W) + c_b

      Y_man[h,w,c] = conv

# print(Y_man.shape)
print(f"Y(Manual): {np.transpose(Y_man, (2,0,1))}")

(1, 2, 2, 3)
Y(Tensorflow): [[[-0.25422177 -0.45924386]
  [-0.2865349  -0.45763057]]

 [[ 0.8020651   1.0614858 ]
  [ 1.3265264   1.0502235 ]]

 [[-0.59098554 -0.9467616 ]
  [-0.1412074  -0.4535703 ]]]
Y(Manual): [[[-0.25422174 -0.45924383]
  [-0.28653494 -0.45763057]]

 [[ 0.80206501  1.06148565]
  [ 1.32652652  1.05022335]]

 [[-0.59098554 -0.94676155]
  [-0.14120743 -0.45357037]]]


In [19]:
import numpy as np
images = np.random.randint(low=0, high=10, size=(2,3,4))
# print(images)

for c in range(4):
  # channel별로 따로봐야, weight, height 형태로 볼 수 있음
  print(images[:,:,c])

# transpose: 차원 재배치
# size=(2,3,4)를 기준으로 각각의 index는 0,1,2
# index를 2,0,1 순으로 변경한다는 의미
images = np.transpose(images, (2,0,1))
# print(images.shape)

for c in range(4):
  print(images[c,:,:])

[[6 1 5]
 [4 4 7]]
[[6 0 8]
 [0 1 1]]
[[2 2 8]
 [0 0 5]]
[[8 1 7]
 [6 5 9]]
[[6 1 5]
 [4 4 7]]
[[6 0 8]
 [0 1 1]]
[[2 2 8]
 [0 0 5]]
[[8 1 7]
 [6 5 9]]


# 5-3: Conv Layers with Activation Functions

## Code.5-3-1. Conv Layers with Activation Functions

In [34]:
import numpy as np
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4 # kernel, color size
images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation='sigmoid')
Y = conv(images)
# print(Y.shape)
print(Y.numpy().shape)
# print(f"Y(Tensorflow): {Y.numpy()}")
# (1, 2, 2, 4) 형태를 출력
# 마치 kernel(R,G,B)에 해당하는 값이 4로 출력됨에 따라
# 결과는 R,G,B,_가 펼쳐진 형태로 print됨

Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print(f"Y(Tensorflow): {Y}")

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()
# print(W.shape, B.shape)

Y_man = np.zeros(shape=(n_H - k_size +1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:,:,:,c]
  c_b = B[c]

  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w+k_size, :]
      conv = np.sum(window*c_W) + c_b
      conv = 1/(1+ np.exp(-conv))

      Y_man[h,w,c] = conv

# print(Y_man.shape)
print(f"Y(Manual): {np.transpose(Y_man, (2,0,1))}")

(1, 2, 2, 3)
Y(Tensorflow): [[[0.47555676 0.59177506]
  [0.5920567  0.43577215]]

 [[0.38109317 0.5119858 ]
  [0.3818958  0.4644952 ]]

 [[0.3690512  0.3923633 ]
  [0.34802017 0.30564323]]]
Y(Manual): [[[0.4755568  0.59177508]
  [0.59205665 0.43577214]]

 [[0.38109319 0.5119858 ]
  [0.38189581 0.46449519]]

 [[0.3690512  0.3923633 ]
  [0.34802019 0.30564324]]]
